import java.awt.Color;
import java.sql.*;
import javax.swing.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Homepage.java
 *
 * Created on 17 Dec, 2017, 10:18:27 AM
 */

/**
 *
 * @author Tushar
 */
public class Homepage extends javax.swing.JFrame {

    /** Creates new form Homepage */
    public Homepage() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        u1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        p1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        t4 = new javax.swing.JTextField();
        p2 = new javax.swing.JPasswordField();
        l1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        r3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.activeCaption);

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Papyrus", 3, 36));
        jLabel1.setForeground(new java.awt.Color(23, 126, 237));
        jLabel1.setText("COMIC BOOK WORLD");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel2.setText("Enter Username");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel3.setText("Enter Password");

        jButton1.setText("Log In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Papyrus", 3, 48));
        jLabel4.setForeground(new java.awt.Color(23, 126, 237));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CBW");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel5.setText("Celebrate your love for comics with us");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 15));
        jLabel6.setText("Comic Book World aims to offer a refreshing and fun shopping experience to fans of all ages");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel7.setText("Create a free account");

        t1.setFont(new java.awt.Font("Arial", 0, 14));
        t1.setForeground(new java.awt.Color(204, 204, 204));
        t1.setText("Enter Your Name Here");
        t1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t1FocusGained(evt);
            }
        });

        t3.setFont(new java.awt.Font("Arial", 0, 14));
        t3.setForeground(new java.awt.Color(204, 204, 204));
        t3.setText("Enter Address Here");
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        t3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t3FocusGained(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel8.setText("Enter Your Birthday");

        t5.setFont(new java.awt.Font("Arial", 0, 14));
        t5.setForeground(new java.awt.Color(204, 204, 204));
        t5.setText("DD");
        t5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t5FocusGained(evt);
            }
        });

        t6.setFont(new java.awt.Font("Arial", 0, 14));
        t6.setForeground(new java.awt.Color(204, 204, 204));
        t6.setText("MM");
        t6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t6FocusGained(evt);
            }
        });

        t7.setFont(new java.awt.Font("Arial", 0, 14));
        t7.setForeground(new java.awt.Color(204, 204, 204));
        t7.setText("YYYY");
        t7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t7FocusGained(evt);
            }
        });

        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Arial", 0, 14));
        r1.setText("Male");

        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r2.setText("Others");

        jButton2.setText("Create Account");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        t4.setFont(new java.awt.Font("Arial", 0, 14));
        t4.setForeground(new java.awt.Color(204, 204, 204));
        t4.setText("Enter Email Address");
        t4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t4FocusGained(evt);
            }
        });

        p2.setFont(new java.awt.Font("Arial", 0, 14));
        p2.setForeground(new java.awt.Color(204, 204, 204));
        p2.setText("Enter Password Here");
        p2.setEchoChar((char)0);
        p2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                p2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                p2FocusLost(evt);
            }
        });

        l1.setForeground(new java.awt.Color(204, 0, 0));

        l2.setFont(new java.awt.Font("Arial", 2, 12));
        l2.setForeground(new java.awt.Color(0, 0, 153));
        l2.setText("Enter As Administrator?");
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
        });

        l3.setForeground(new java.awt.Color(204, 0, 0));

        t2.setFont(new java.awt.Font("Arial", 0, 14));
        t2.setForeground(new java.awt.Color(204, 204, 204));
        t2.setText("Enter Your Username Here");
        t2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t2FocusGained(evt);
            }
        });

        buttonGroup1.add(r3);
        r3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        r3.setText("Female");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(u1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addComponent(jLabel3)))
                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1169, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1169, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(502, 502, 502)
                .addComponent(l2)
                .addContainerGap(538, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(63, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(299, 299, 299))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(t1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(r1)
                                    .addGap(43, 43, 43)
                                    .addComponent(r3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                    .addComponent(r2)
                                    .addGap(23, 23, 23))
                                .addComponent(t4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(l1)
                                        .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)))
                                .addComponent(t2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                                .addComponent(t3, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
                            .addGap(148, 148, 148)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(u1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l3, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l1)
                        .addGap(18, 18, 18)
                        .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r1)
                    .addComponent(r3)
                    .addComponent(r2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(16, 16, 16)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(l2)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try
{
    Class.forName("java.sql.Driver");
    Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/dbmsproject","root","");
    Statement s1=c.createStatement();
    String name=t1.getText(),user=t2.getText(), pass=p2.getText(),address=t3.getText(), email=t4.getText(),day=t5.getText(),month=t6.getText(),year=t7.getText(),gen="0";

   String bd=year+month+day;

    if(r1.isSelected()==true)
    {
        gen="m";
    }
    else if(r3.isSelected()==true)
    {
        gen="f";
    }
   else if(r2.isSelected()==true)
    {
        gen="o";
    }
    String x="Insert into customer (name,username,password,address,email,birthdate,gender) values('"+(name)+"','"+(user)+"','"+(pass)+"','"+(address)+"','"+(email)+"','"+(bd)+"','"+(gen)+"')";
    s1.executeUpdate(x);
    String sql="Select custid from customer where username='"+(user)+"' and name='"+(name)+"'";
    ResultSet rs=s1.executeQuery(sql);
    int custid=0;
    while(rs.next())
    {
        custid=rs.getInt(1);
    }
    
    JOptionPane.showMessageDialog(this,"Account Successfully Created");
    s1.close();c.close();
    dispose();
    new ShoppingWindow(custid).setVisible(true);
    
    
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this, e.getMessage());
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t1FocusGained
t1.setText("");
t1.setForeground(Color.black);



// TODO add your handling code here:
}//GEN-LAST:event_t1FocusGained

    private void p2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_p2FocusGained
p2.setEchoChar('*');
p2.setText("");
p2.setForeground(Color.black);


// TODO add your handling code here:
}//GEN-LAST:event_p2FocusGained

    private void t3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t3FocusGained
t3.setText("");
t3.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_t3FocusGained

    private void t4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t4FocusGained
t4.setText("");
t4.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_t4FocusGained

    private void t5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t5FocusGained
t5.setText("");
t5.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_t5FocusGained

    private void t6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t6FocusGained
t6.setText("");
t6.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_t6FocusGained

    private void t7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t7FocusGained
t7.setText("");
t7.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_t7FocusGained

    private void p2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_p2FocusLost
        String pass=p2.getText();
        if(!((pass.length()>=8) && (pass.length()<=15))){
            l1.setText("Password should be between 8 to 15 characters");
            p2.requestFocus();
        }
        else if(pass.contains(" ")){
            l1.setText("Password shouldn't contain any space");
            p2.requestFocus();
        }
        else
        {
            int cnum=0,clow=0,cup=0;
            for(int i=0;i<10;i++){
                String str=Integer.toString(i);
                if(pass.contains(str)){
                    cnum=1;
                    break;
                }
            }
            for(int i=65;i<=90;i++){
                char c=(char)i;
                String str=Character.toString(c);
                if(pass.contains(str)){
                    cup=1;
                    break;
                }
            }
            for(int i=90;i<=122;i++){
                char c=(char)i;
                String str=Character.toString(c);
                if(pass.contains(str)){
                    clow=1;
                    break;
                }
            }
            if(cnum==0)
            {
                l1.setText("Password should have digits");
                p2.requestFocus();
            }
            else if(clow==0)
            {
                l1.setText("Password should have lowercase characters");
                p2.requestFocus();
            }
            else if(cup==0)
            {
                l1.setText("Password should have uppercase characters");
                p2.requestFocus();
            }
            else
            {
                l1.setText("");
            }
        }

        
        // TODO add your handling code here:
}//GEN-LAST:event_p2FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  String user=u1.getText();

  String pass=p1.getText();
  if((pass.compareTo("")==0)|| (user.compareTo("")==0)){
      l3.setText("Please Enter Username And Password Fields");
  }
  else if((pass.compareTo("")!=0) && (user.compareTo("")!=0)){
  String sql="Select custid,name,username,password from customer";

  try{
      Class.forName("java.sql.Driver");
      Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/dbmsproject","root","");
      Statement s=c.createStatement();
      ResultSet rs=s.executeQuery(sql);
      String n="",pd="",v="",username="";
      int custid=0;
      while(rs.next())
      {
          custid=rs.getInt(1);
          v=rs.getString(2);
          n=v.toLowerCase();
          username=rs.getString(3);
          pd=rs.getString(4);
       if((username.equals(user))&& (pd.equals(pass)))
      {
          JOptionPane.showMessageDialog(this,"Welcome");
          dispose();
          new ShoppingWindow(custid).setVisible(true);
      }
      else{
           l3.setText("The entered password or username is wrong. Try again");
      }
      }
     
      rs.close(); s.close();c.close();

  }
  catch(Exception e){
      JOptionPane.showMessageDialog(this,e.getMessage());
  }
  }    // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
dispose();
new AdminWindow().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_l2MouseClicked

    private void t2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t2FocusGained
t2.setText("");
t2.setForeground(Color.black);
        // TODO add your handling code here:
    }//GEN-LAST:event_t2FocusGained

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JPasswordField p1;
    private javax.swing.JPasswordField p2;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField u1;
    // End of variables declaration//GEN-END:variables

}
